# Generated by Django 4.2.27 on 2025-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exclude_from_auto_assignment",
            field=models.BooleanField(
                default=False,
                help_text="If True, user will NOT be auto-assigned chores at distribution time, but can still claim or be manually assigned",
            ),
        ),
    ]
