# Generated by Django 4.2.27 on 2025-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0009_arcadecompletion_arcadesession_arcadehighscore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="one_time_due_date",
            field=models.DateField(
                blank=True,
                help_text="For ONE_TIME tasks: optional due date. If not set, task never becomes overdue.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chore",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("every_n_days", "Every N Days"),
                    ("cron", "Cron"),
                    ("rrule", "RRULE"),
                    ("one_time", "One-Time Task"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="choredependency",
            name="offset_hours",
            field=models.IntegerField(
                default=0,
                help_text="Hours after parent completion to spawn this child chore",
            ),
        ),
        migrations.AlterField(
            model_name="choretemplate",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("every_n_days", "Every N Days"),
                    ("cron", "Cron"),
                    ("rrule", "RRULE"),
                    ("one_time", "One-Time Task"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
