# Generated by Django 4.2.27 on 2025-12-11 04:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0010_add_one_time_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PianoScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="Number of tiles successfully hit",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                (
                    "hard_mode",
                    models.BooleanField(
                        default=False, help_text="Was this score achieved in hard mode?"
                    ),
                ),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piano_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "piano_scores",
                "ordering": ["-score", "achieved_at"],
                "indexes": [
                    models.Index(
                        fields=["-score", "achieved_at"],
                        name="piano_score_score_4deac0_idx",
                    ),
                    models.Index(
                        fields=["user", "-score"], name="piano_score_user_id_740fdf_idx"
                    ),
                    models.Index(
                        fields=["hard_mode", "-score"],
                        name="piano_score_hard_mo_1a35ef_idx",
                    ),
                ],
            },
        ),
    ]
